spring:
  datasource:
    sql-script-encoding: utf-8
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/crm_clue?allowPublicKeyRetrieval=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      pool-name: crm-clue-hikaricp
      max-lifetime: 1765000
      maximum-pool-size: 64
      minimum-idle: 4
  application:
    name: crm-clue
mybatis-plus:
  type-aliases-package: com.zm.crm.crmclue.entity
server:
  port: 8003
#  servlet:
#    context-path: /crm-clue
# swagger文档访问路径
# http://localhost:8003/swagger-ui/index.html
# http://localhost:8003/doc.html
swagger:
  enabled: true
logging:
  level:
    com.zm.crm.crmclue: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace

feign:
  sentinel:
    enabled: true
  hystrix:
    enabled: true
