spring:
  application:
    name: hello-service

dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.zm #扫描@DubboService注解所在的包
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: 1${server.port}
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost


