spring:
  datasource:
    sql-script-encoding: utf-8
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/crm_activity?allowPublicKeyRetrieval=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      pool-name: crm-activity-hikaricp
      max-lifetime: 1765000
      maximum-pool-size: 64
      minimum-idle: 4
  application:
    name: crm-activity
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8080
      datasource:
        ds:
          nacos:
            server-addr: localhost:8848
            data-id: ${spring.application.name}-flow-rules
            rule-type: flow
            data-type: json



mybatis-plus:
  type-aliases-package: com.zm.crm.crmactivity.entity
server:
  port: 8001
#  servlet:
#    context-path: /crm-activity
# swagger文档访问路径
# http://localhost:8001/swagger-ui/index.html
# http://localhost:8001/doc.html
swagger:
  enabled: true
logging:
  level:
    com.zm.crm.crmactivity: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace

