spring:
  datasource:
    sql-script-encoding: utf-8
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/crm_business?allowPublicKeyRetrieval=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      pool-name: crm-business-hikaricp
      max-lifetime: 1765000
      maximum-pool-size: 64
      minimum-idle: 4
  application:
    name: crm-business
mybatis-plus:
  type-aliases-package: com.zm.crm.crmbusiness.entity
server:
  port: 8002
#  servlet:
#    context-path: /crm-business
# swagger文档访问路径
# http://localhost:8002/swagger-ui/index.html
# http://localhost:8002/doc.html
swagger:
  enabled: true
logging:
  level:
    com.zm.crm.crmbusiness: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace