spring:
  datasource:
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql:///cloud_order?serverTimezone=Asia/Shanghai
  application:
    name: orderservice
  cloud:
    nacos:
      discovery:
        cluster-name: HZ
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    com.order: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则 优先同集群中的
feign:
  httpclient:
    enabled: true #支持httpClient的开关
    max-connections: 200 #最大连接数
    max-connections-per-route: 50 #单个路劲的最大连接数

